### ISSUE TITLE
Add an ODBC data source implementation

### ISSUE THREAD

**Issue by joosbuijsNL** [schuderer/mllaunchpad#109]
*   ML Launchpad version: 1.0.0 RC1
*   Operating System: Windows 10 

### Description

It would be helpful if ODBC connections would also be supported 'out of the box' by MLLP.

_Note_: i have a rough data source implementation for ODBC's which I can contribute if necessary (but it's not that difficult actually).

_Bonus idea_: add more logic of the data source implementations to the abstract class. I copied my approach from the Impala example but 95% of the code remained the same... In essence only the name, an import and the connect function reference is different...

**Comment by schuderer** [comment]
Thanks for bringing this up. Could you take a look at the recordsdatasource in the examples and check whether this already fulfills your requirement? It uses the pretty flexible [Records ](https://github.com/kennethreitz-archive/records) library to support many database systems (but not sure if ODBC).

Haha, like your *Bonus idea*. 👍 We indeed have a bit of an ad-hoc approach to RDBMS connections right now, as there's only a single one included in core MLLP (trying to do abstracting when it is needed, not before -- which could be now ;) ). Fortunately for us, Python has quite nice standardization through PEP 249, and your suggestion makes a lot of sense! Maybe there's even a possibility to create a rather generic DataSource-subclass for most types of database systems, possibly based on recordsdatasource (if it makes sense). **Pull request welcome. :)**

Regarding the base class: If we go the route of several separate datasources for separate database systems, I would, for now, rather put the common database-specific functionality in utility functions than in the DataSource base class (the base class is meant for any kind of data source -- relational databases, but also csv biles, binary files, potentially XML, json, ...), and I also shy away from creating a potentially deep hierarchy like DataSource->DBMSDataSource->ODBCDataSource. But this is hypothetical -- maybe most can be dealt with in one single, but more generic, DataSource.

Edit: By the way, the user would not see a difference if we put it all into one huge DBMSDataSource vs several DBMS-specific DataSources, due to the config's "type" not being a 1:1 correspondence to DataSource subclasses ("type" is used for locating DataSource subclasses that can "service" that particular type, and any DataSource subclass can announce to service as many types as it likes. BTW: conflicts are handled in a "last-one-wins" manner)

**Comment by schuderer** [comment]
I'm currently looking int making this available as a generic DataSource using SQLAlchemy.

This might solve #4 that had to be reopened and needs to be tackled one way or the other.
